In [132]:
import pandas as pd

In [133]:
df=pd.read_csv('k2pandc_2025.10.03_22.14.54.csv')

In [134]:
df

,pl_name,hostname,default_flag,disposition,disp_refname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,...,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,rowupdate,pl_pubdate,releasedate
0,BD+20 594 b,BD+20 594,0,CONFIRMED,Espinoza et al. 2016,1,1,Transit,2016,K2,...,-0.012,9.368,0.018,-0.018,10.86440,0.000249,-0.000249,2018-04-25,2018-03,2018-02-15
1,BD+20 594 b,BD+20 594,0,CONFIRMED,Espinoza et al. 2016,1,1,Transit,2016,K2,...,-0.012,9.368,0.018,-0.018,10.86440,0.000249,-0.000249,2018-04-25,2016-10,2016-07-28
2,BD+20 594 b,BD+20 594,1,CONFIRMED,Espinoza et al. 2016,1,1,Transit,2016,K2,...,-0.012,9.368,0.018,-0.018,10.86440,0.000249,-0.000249,2018-04-25,2017-03,2018-04-26
3,EPIC 201111557.01,EPIC 201111557,1,CANDIDATE,Livingston et al. 2018,1,0,Transit,2018,K2,...,-0.046,9.220,0.019,-0.019,11.39950,0.001307,-0.001307,2018-08-02,2018-08,2018-08-02
4,EPIC 201111557.01,EPIC 201111557,0,CANDIDATE,Livingston et al. 2018,1,0,Transit,2018,K2,...,-0.046,9.220,0.019,-0.019,11.39950,0.001307,-0.001307,2018-02-15,2018-03,2018-02-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3999,WASP-85 A b,WASP-85 A,0,CONFIRMED,Mo&#x10D;nik et al. 2016,2,1,Transit,2016,K2,...,-0.010,8.733,0.026,-0.026,10.62410,0.000959,-0.000959,2019-09-05,2019-09,2019-09-05
4000,Wolf 503 b,Wolf 503,1,CONFIRMED,Peterson et al. 2018,1,1,Transit,2018,K2,...,-0.030,7.617,0.023,-0.023,9.89816,0.000337,-0.000337,2022-05-23,2021-12,2022-05-23
4001,Wolf 503 b,Wolf 503,0,CONFIRMED,Peterson et al. 2018,1,1,Transit,2018,K2,...,-0.030,7.617,0.023,-0.023,9.89816,0.000337,-0.000337,2018-09-04,2018-11,2018-09-06
4002,Wolf 503 b,Wolf 503,0,CONFIRMED,Peterson et al. 2018,1,1,Transit,2018,K2,...,-0.030,7.617,0.023,-0.023,9.89816,0.000337,-0.000337,2023-04-17,2023-04,2023-04-17
4003,Wolf 503 b,Wolf 503,0,CONFIRMED,Peterson et al. 2018,1,1,Transit,2018,K2,...,-0.030,7.617,0.023,-0.023,9.89816,0.000337,-0.000337,2025-09-17,2017-07,2025-08-28

In [135]:
# List of useful columns we want to KEEP
useful_cols = [
    # Planetary features
    "pl_orbper", "pl_orbsmax", "pl_rade", "pl_bmasse",
    "pl_orbeccen", "pl_insol", "pl_eqt",

    # Stellar features
    "st_teff", "st_rad", "st_mass", "st_met", "st_logg",
    "sy_vmag", "sy_kmag", "sy_gaiamag", "sy_dist",

    # System context
    "sy_snum", "sy_pnum", "ttv_flag",

    # Target column (label for classification)
    "disposition"
]

# Keep only useful columns
df_clean = df[useful_cols].copy()

# Show result
print("Original shape:", df.shape)
print("After dropping unuseful columns:", df_clean.shape)
print(df_clean.head())

Original shape: (4004, 94)
After dropping unuseful columns: (4004, 20)
   pl_orbper  pl_orbsmax   pl_rade  pl_bmasse  pl_orbeccen  pl_insol  pl_eqt  \
0  41.688644         NaN  2.355454        NaN          NaN       NaN     NaN
1  41.685500       0.241  2.230000    16.3000          0.0       NaN   546.0
2  41.685500         NaN  2.578070    22.2481          0.0       NaN     NaN
3   2.301830         NaN  1.120000        NaN          NaN       NaN  1054.0
4   2.302368         NaN  1.312588        NaN          NaN       NaN     NaN

   st_teff    st_rad   st_mass  st_met  st_logg  sy_vmag  sy_kmag  sy_gaiamag  \
0  5703.00  0.956122  0.963861   -0.06  4.38000   10.849    9.368     10.8644
1  5766.00  0.928000  0.961000   -0.15  4.50000   10.849    9.368     10.8644
2  5766.00  1.080000  1.670000   -0.15  4.50000   10.849    9.368     10.8644
3  4616.52  0.762602  0.730000   -0.03  4.53679   11.727    9.220     11.3995
4  4720.00  0.710995       NaN   -0.06  4.50000   11.727    9.220     11.3995

    sy_dist  sy_snum  sy_pnum  ttv_flag disposition
0  179.4610        1        1         0   CONFIRMED
1  179.4610        1        1         0   CONFIRMED
2  179.4610        1        1         0   CONFIRMED
3   97.1795        1        0         0   CANDIDATE
4   97.1795        1        0         0   CANDIDATE

In [136]:
df_clean

,pl_orbper,pl_orbsmax,pl_rade,pl_bmasse,pl_orbeccen,pl_insol,pl_eqt,st_teff,st_rad,st_mass,st_met,st_logg,sy_vmag,sy_kmag,sy_gaiamag,sy_dist,sy_snum,sy_pnum,ttv_flag,disposition
0,41.688644,NaN,2.355454,NaN,NaN,NaN,NaN,5703.00,0.956122,0.963861,-0.06,4.38000,10.849,9.368,10.86440,179.4610,1,1,0,CONFIRMED
1,41.685500,0.24100,2.230000,16.3000,0.000,NaN,546.00,5766.00,0.928000,0.961000,-0.15,4.50000,10.849,9.368,10.86440,179.4610,1,1,0,CONFIRMED
2,41.685500,NaN,2.578070,22.2481,0.000,NaN,NaN,5766.00,1.080000,1.670000,-0.15,4.50000,10.849,9.368,10.86440,179.4610,1,1,0,CONFIRMED
3,2.301830,NaN,1.120000,NaN,NaN,NaN,1054.00,4616.52,0.762602,0.730000,-0.03,4.53679,11.727,9.220,11.39950,97.1795,1,0,0,CANDIDATE
4,2.302368,NaN,1.312588,NaN,NaN,NaN,NaN,4720.00,0.710995,NaN,-0.06,4.50000,11.727,9.220,11.39950,97.1795,1,0,0,CANDIDATE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3999,2.655676,NaN,11.100000,NaN,NaN,NaN,NaN,NaN,0.884000,NaN,NaN,NaN,10.720,8.733,10.62410,141.8870,2,1,0,CONFIRMED
4000,6.001270,0.05706,2.043000,6.2600,0.410,NaN,790.00,4716.00,0.689000,0.688000,-0.47,4.62000,10.270,7.617,9.89816,44.5260,1,1,0,CONFIRMED
4001,6.001180,0.05710,2.030000,NaN,NaN,69.6000,805.00,4716.00,0.690000,0.688000,-0.47,4.62000,10.270,7.617,9.89816,44.5260,1,1,0,CONFIRMED
4002,6.001270,0.05712,2.043000,6.2700,0.409,64.7000,789.00,4716.00,0.689000,0.688000,-0.47,NaN,10.270,7.617,9.89816,44.5260,1,1,0,CONFIRMED
4003,NaN,NaN,1.757520,NaN,NaN,12.6807,481.29,4759.00,0.641805,NaN,NaN,4.70975,10.270,7.617,9.89816,44.5260,1,1,0,CONFIRMED

In [137]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4004 entries, 0 to 4003
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pl_orbper    3960 non-null   float64
 1   pl_orbsmax   820 non-null    float64
 2   pl_rade      3173 non-null   float64
 3   pl_bmasse    435 non-null    float64
 4   pl_orbeccen  429 non-null    float64
 5   pl_insol     630 non-null    float64
 6   pl_eqt       854 non-null    float64
 7   st_teff      2892 non-null   float64
 8   st_rad       3874 non-null   float64
 9   st_mass      2102 non-null   float64
 10  st_met       1698 non-null   float64
 11  st_logg      2356 non-null   float64
 12  sy_vmag      3962 non-null   float64
 13  sy_kmag      3981 non-null   float64
 14  sy_gaiamag   3948 non-null   float64
 15  sy_dist      3879 non-null   float64
 16  sy_snum      4004 non-null   int64
 17  sy_pnum      4004 non-null   int64
 18  ttv_flag     4004 non-null   int64
 19  disposition  4004 non-null   object
dtypes: float64(16), int64(3), object(1)
memory usage: 625.8+ KB

In [138]:
df_clean.isnull().sum()

pl_orbper        44
pl_orbsmax     3184
pl_rade         831
pl_bmasse      3569
pl_orbeccen    3575
pl_insol       3374
pl_eqt         3150
st_teff        1112
st_rad          130
st_mass        1902
st_met         2306
st_logg        1648
sy_vmag          42
sy_kmag          23
sy_gaiamag       56
sy_dist         125
sy_snum           0
sy_pnum           0
ttv_flag          0
disposition       0
dtype: int64

In [90]:
df_clean['disposition'].value_counts()

disposition
CONFIRMED         2315
CANDIDATE         1374
FALSE POSITIVE     293
REFUTED             22
Name: count, dtype: int64

In [91]:
df_TOI=pd.read_csv('TOI_2025.10.03_22.14.23.csv',comment='#')

In [92]:
df_TOI

,toi,tid,tfopwg_disp,rastr,ra,decstr,dec,st_pmra,st_pmraerr1,st_pmraerr2,...,st_logg,st_loggerr1,st_loggerr2,st_logglim,st_rad,st_raderr1,st_raderr2,st_radlim,toi_created,rowupdate
0,1000.01,50365310,FP,07h29m25.85s,112.357708,-12d41m45.46s,-12.695960,-5.964,0.085,-0.085,...,4.19,0.07,-0.07,0,2.169860,0.072573,-0.072573,0,2019-07-24 15:58:33,2024-09-09 10:08:01
1,1001.01,88863718,PC,08h10m19.31s,122.580465,-05d30m49.87s,-5.513852,-4.956,0.102,-0.102,...,4.03,0.09,-0.09,0,2.010000,0.090000,-0.090000,0,2019-07-24 15:58:33,2023-04-03 14:31:04
2,1002.01,124709665,FP,06h58m54.47s,104.726966,-10d34m49.64s,-10.580455,-1.462,0.206,-0.206,...,NaN,NaN,NaN,0,5.730000,NaN,NaN,0,2019-07-24 15:58:33,2022-07-11 16:02:02
3,1003.01,106997505,FP,07h22m14.39s,110.559945,-25d12m25.26s,-25.207017,-0.939,0.041,-0.041,...,4.15,1.64,-1.64,0,NaN,NaN,NaN,0,2019-07-24 15:58:33,2022-02-23 10:10:02
4,1004.01,238597883,FP,08h08m42.77s,122.178195,-48d48m10.12s,-48.802811,-4.496,0.069,-0.069,...,4.14,0.07,-0.07,0,2.150000,0.060000,-0.060000,0,2019-07-24 15:58:33,2024-09-09 10:08:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7698,995.01,317951248,FP,07h23m14.75s,110.811443,+05d33m46.26s,5.562850,2.061,0.405,-0.405,...,NaN,NaN,NaN,0,NaN,NaN,NaN,0,2019-07-24 15:58:33,2021-10-29 12:59:15
7699,996.01,142918609,FP,07h57m23.99s,119.349948,-19d30m57.65s,-19.516015,-3.900,0.848,-0.848,...,NaN,NaN,NaN,0,2.050000,NaN,NaN,0,2019-07-24 15:58:33,2021-10-29 12:59:15
7700,997.01,341729521,FP,08h05m16.69s,121.319521,-59d34m47.27s,-59.579798,-44.770,0.044,-0.044,...,4.52,0.08,-0.08,0,0.926261,0.045789,-0.045789,0,2019-07-24 15:58:33,2024-09-09 10:08:01
7701,998.01,54390047,FP,07h53m16.69s,118.319555,-14d13m07.76s,-14.218823,-1.706,0.069,-0.069,...,4.01,0.07,-0.07,0,2.349860,0.091578,-0.091578,0,2019-07-24 15:58:33,2024-09-09 10:08:01
7702,999.01,341186896,FP,07h55m27.38s,118.864086,-58d13m19.42s,-58.222060,-17.190,0.042,-0.042,...,4.35,0.09,-0.09,0,1.300000,0.050000,-0.050000,0,2019-07-24 15:58:33,2024-09-09 10:08:01

In [93]:
useful_cols = [
    # Planetary
    "pl_orbper", "pl_trandurh", "pl_trandep", 
    "pl_rade", "pl_insol", "pl_eqt",

    # Stellar
    "st_teff", "st_logg", "st_rad", "st_tmag", "st_dist",

    # Target
    "tfopwg_disp"
]

# Keep only useful
df_clean_toi = df_TOI[useful_cols].copy()

print("Original shape:", df.shape)
print("After cleaning:", df_clean_toi.shape)
print(df_clean_toi.head())

Original shape: (4004, 94)
After cleaning: (7703, 12)
   pl_orbper  pl_trandurh   pl_trandep    pl_rade      pl_insol       pl_eqt  \
0   2.171348      2.01722   656.886099   5.818163  22601.948581  3127.204052
1   1.931646      3.16600  1286.000000  11.215400  44464.500000  4045.000000
2   1.867557      1.40800  1500.000000  23.752900   2860.610000  2037.000000
3   2.743230      3.16700   383.410000        NaN   1177.360000  1631.000000
4   3.573014      3.37000   755.000000  11.311300  54679.300000  4260.000000

   st_teff  st_logg   st_rad   st_tmag   st_dist tfopwg_disp
0  10249.0     4.19  2.16986  9.604000   485.735          FP
1   7070.0     4.03  2.01000  9.423440   295.862          PC
2   8924.0      NaN  5.73000  9.299501   943.109          FP
3   5388.5     4.15      NaN  9.300300  7728.170          FP
4   9219.0     4.14  2.15000  9.135500   356.437          FP

In [94]:
df_clean_toi

,pl_orbper,pl_trandurh,pl_trandep,pl_rade,pl_insol,pl_eqt,st_teff,st_logg,st_rad,st_tmag,st_dist,tfopwg_disp
0,2.171348,2.017220,656.886099,5.818163,22601.948581,3127.204052,10249.0,4.19,2.169860,9.604000,485.735,FP
1,1.931646,3.166000,1286.000000,11.215400,44464.500000,4045.000000,7070.0,4.03,2.010000,9.423440,295.862,PC
2,1.867557,1.408000,1500.000000,23.752900,2860.610000,2037.000000,8924.0,NaN,5.730000,9.299501,943.109,FP
3,2.743230,3.167000,383.410000,NaN,1177.360000,1631.000000,5388.5,4.15,NaN,9.300300,7728.170,FP
4,3.573014,3.370000,755.000000,11.311300,54679.300000,4260.000000,9219.0,4.14,2.150000,9.135500,356.437,FP
...,...,...,...,...,...,...,...,...,...,...,...,...
7698,3.443800,2.572000,7260.750000,NaN,1413.670000,1708.000000,4805.2,NaN,NaN,10.078100,1080.880,FP
7699,14.537800,6.826000,4040.000000,16.052300,NaN,NaN,8007.0,NaN,2.050000,9.792500,379.693,FP
7700,8.413486,3.556833,17479.605331,20.510696,127.916421,857.731431,5786.0,4.52,0.926261,9.772700,113.667,FP
7701,0.941436,1.360700,339.912662,4.529209,41562.587811,3641.626449,8322.0,4.01,2.349860,9.695200,482.278,FP
7702,1.507896,2.759000,1839.000000,5.530910,9662.800000,2762.000000,6635.0,4.35,1.300000,9.617100,180.020,FP

In [95]:
df_clean_toi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7703 entries, 0 to 7702
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pl_orbper    7596 non-null   float64
 1   pl_trandurh  7703 non-null   float64
 2   pl_trandep   7703 non-null   float64
 3   pl_rade      7197 non-null   float64
 4   pl_insol     7527 non-null   float64
 5   pl_eqt       7392 non-null   float64
 6   st_teff      7542 non-null   float64
 7   st_logg      6847 non-null   float64
 8   st_rad       7196 non-null   float64
 9   st_tmag      7703 non-null   float64
 10  st_dist      7488 non-null   float64
 11  tfopwg_disp  7703 non-null   object
dtypes: float64(11), object(1)
memory usage: 722.3+ KB

In [96]:
df_clean_toi['tfopwg_disp'].value_counts()

tfopwg_disp
PC     4679
FP     1197
CP      684
KP      583
APC     462
FA       98
Name: count, dtype: int64

In [97]:
import pandas as pd

# Load dataset (skip comment rows)
df_cumu = pd.read_csv("cumulative_2025.10.03_22.12.52.csv", comment="#")

# Columns to keep (main science + classification target)
useful_cols = [
    # Identifiers
    "kepid", "kepoi_name", "kepler_name",

    # Target label
    "koi_disposition",    # Confirmed / Candidate / False Positive

    # Planet orbital & transit parameters
    "koi_period",    # Orbital Period [days]
    "koi_eccen",     # Eccentricity
    "koi_impact",    # Impact Parameter
    "koi_duration",  # Transit Duration [hrs]
    "koi_depth",     # Transit Depth [ppm]
    "koi_ror",       # Planet-Star Radius Ratio
    "koi_prad",      # Planetary Radius [Earth radii]
    "koi_sma",       # Semi-Major Axis [AU]
    "koi_incl",      # Inclination [deg]
    "koi_teq",       # Equilibrium Temp [K]
    "koi_insol",     # Insolation Flux [Earth flux]
    "koi_dor",       # Distance/Radius ratio

    # Stellar parameters
    "koi_steff",     # Stellar Effective Temp [K]
    "koi_slogg",     # Surface Gravity
    "koi_smet",      # Metallicity
    "koi_srad",      # Stellar Radius [Solar radii]
    "koi_smass",     # Stellar Mass [Solar mass]
    "koi_sage",      # Stellar Age [Gyr]

    # Photometry
    "koi_kepmag", "koi_gmag", "koi_rmag",
    "koi_imag", "koi_zmag", "koi_jmag",
    "koi_hmag", "koi_kmag"
]

# Drop everything else
df_clean_cumu = df_cumu[useful_cols].copy()

print("Original shape:", df.shape)
print("Cleaned shape:", df_clean_cumu.shape)
print(df_clean_cumu.head())

Original shape: (4004, 94)
Cleaned shape: (9564, 30)
      kepid kepoi_name   kepler_name koi_disposition  koi_period  koi_eccen  \
0  10797460  K00752.01  Kepler-227 b       CONFIRMED    9.488036        0.0
1  10797460  K00752.02  Kepler-227 c       CONFIRMED   54.418383        0.0
2  10811496  K00753.01           NaN       CANDIDATE   19.899140        0.0
3  10848459  K00754.01           NaN  FALSE POSITIVE    1.736952        0.0
4  10854555  K00755.01  Kepler-664 b       CONFIRMED    2.525592        0.0

   koi_impact  koi_duration  koi_depth   koi_ror  ...  koi_smass  koi_sage  \
0       0.146       2.95750      615.8  0.022344  ...      0.919       NaN
1       0.586       4.50700      874.8  0.027954  ...      0.919       NaN
2       0.969       1.78220    10829.0  0.154046  ...      0.961       NaN
3       1.276       2.40641     8079.2  0.387394  ...      0.836       NaN
4       0.701       1.65450      603.3  0.024064  ...      1.095       NaN

   koi_kepmag  koi_gmag  koi_rmag  koi_imag  koi_zmag  koi_jmag  koi_hmag  \
0      15.347    15.890    15.270    15.114    15.006    14.082    13.751
1      15.347    15.890    15.270    15.114    15.006    14.082    13.751
2      15.436    15.943    15.390    15.220    15.166    14.254    13.900
3      15.597    16.100    15.554    15.382    15.266    14.326    13.911
4      15.509    16.015    15.468    15.292    15.241    14.366    14.064

   koi_kmag
0    13.648
1    13.648
2    13.826
3    13.809
4    13.952

[5 rows x 30 columns]

In [98]:
df_clean_cumu

,kepid,kepoi_name,kepler_name,koi_disposition,koi_period,koi_eccen,koi_impact,koi_duration,koi_depth,koi_ror,...,koi_smass,koi_sage,koi_kepmag,koi_gmag,koi_rmag,koi_imag,koi_zmag,koi_jmag,koi_hmag,koi_kmag
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,9.488036,0.0,0.146,2.95750,615.8,0.022344,...,0.919,NaN,15.347,15.890,15.270,15.114,15.006,14.082,13.751,13.648
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,54.418383,0.0,0.586,4.50700,874.8,0.027954,...,0.919,NaN,15.347,15.890,15.270,15.114,15.006,14.082,13.751,13.648
2,10811496,K00753.01,NaN,CANDIDATE,19.899140,0.0,0.969,1.78220,10829.0,0.154046,...,0.961,NaN,15.436,15.943,15.390,15.220,15.166,14.254,13.900,13.826
3,10848459,K00754.01,NaN,FALSE POSITIVE,1.736952,0.0,1.276,2.40641,8079.2,0.387394,...,0.836,NaN,15.597,16.100,15.554,15.382,15.266,14.326,13.911,13.809
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,2.525592,0.0,0.701,1.65450,603.3,0.024064,...,1.095,NaN,15.509,16.015,15.468,15.292,15.241,14.366,14.064,13.952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9559,10090151,K07985.01,NaN,FALSE POSITIVE,0.527699,0.0,1.252,3.22210,1579.2,0.297633,...,1.005,NaN,14.082,14.082,13.501,13.299,13.177,12.200,11.814,11.756
9560,10128825,K07986.01,NaN,CANDIDATE,1.739849,0.0,0.043,3.11400,48.5,0.006379,...,1.075,NaN,14.757,15.189,14.687,14.571,14.484,13.641,13.339,13.261
9561,10147276,K07987.01,NaN,FALSE POSITIVE,0.681402,0.0,0.147,0.86500,103.6,0.009444,...,1.104,NaN,15.385,15.853,15.347,15.185,15.158,14.220,13.913,13.844
9562,10155286,K07988.01,NaN,CANDIDATE,333.486169,0.0,0.214,3.19900,639.1,0.022590,...,2.190,NaN,10.998,11.733,10.880,10.682,10.578,9.501,9.027,8.921
9563,10156110,K07989.01,NaN,FALSE POSITIVE,4.856035,0.0,0.134,3.07800,76.7,0.008076,...,1.260,NaN,14.826,15.210,14.781,14.662,14.647,13.830,13.522,13.512

In [99]:
df_clean_cumu.isnull().sum()

kepid                 0
kepoi_name            0
kepler_name        6817
koi_disposition       0
koi_period            0
koi_eccen           363
koi_impact          363
koi_duration          0
koi_depth           363
koi_ror             363
koi_prad            363
koi_sma             363
koi_incl            364
koi_teq             363
koi_insol           321
koi_dor             363
koi_steff           363
koi_slogg           363
koi_smet            386
koi_srad            363
koi_smass           363
koi_sage           9564
koi_kepmag            1
koi_gmag             41
koi_rmag              9
koi_imag            154
koi_zmag            613
koi_jmag             25
koi_hmag             25
koi_kmag             25
dtype: int64

In [100]:
drop_col=['kepler_name','koi_sage']
df_clean_cumu.drop(drop_col,axis=1,inplace=True)

In [101]:
df_clean_cumu.isnull().sum()

kepid                0
kepoi_name           0
koi_disposition      0
koi_period           0
koi_eccen          363
koi_impact         363
koi_duration         0
koi_depth          363
koi_ror            363
koi_prad           363
koi_sma            363
koi_incl           364
koi_teq            363
koi_insol          321
koi_dor            363
koi_steff          363
koi_slogg          363
koi_smet           386
koi_srad           363
koi_smass          363
koi_kepmag           1
koi_gmag            41
koi_rmag             9
koi_imag           154
koi_zmag           613
koi_jmag            25
koi_hmag            25
koi_kmag            25
dtype: int64

In [102]:
df_clean_cumu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 28 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kepid            9564 non-null   int64
 1   kepoi_name       9564 non-null   object
 2   koi_disposition  9564 non-null   object
 3   koi_period       9564 non-null   float64
 4   koi_eccen        9201 non-null   float64
 5   koi_impact       9201 non-null   float64
 6   koi_duration     9564 non-null   float64
 7   koi_depth        9201 non-null   float64
 8   koi_ror          9201 non-null   float64
 9   koi_prad         9201 non-null   float64
 10  koi_sma          9201 non-null   float64
 11  koi_incl         9200 non-null   float64
 12  koi_teq          9201 non-null   float64
 13  koi_insol        9243 non-null   float64
 14  koi_dor          9201 non-null   float64
 15  koi_steff        9201 non-null   float64
 16  koi_slogg        9201 non-null   float64
 17  koi_smet         9178 non-null   float64
 18  koi_srad         9201 non-null   float64
 19  koi_smass        9201 non-null   float64
 20  koi_kepmag       9563 non-null   float64
 21  koi_gmag         9523 non-null   float64
 22  koi_rmag         9555 non-null   float64
 23  koi_imag         9410 non-null   float64
 24  koi_zmag         8951 non-null   float64
 25  koi_jmag         9539 non-null   float64
 26  koi_hmag         9539 non-null   float64
 27  koi_kmag         9539 non-null   float64
dtypes: float64(25), int64(1), object(2)
memory usage: 2.0+ MB

In [103]:
df_clean_cumu['kepoi_name'].value_counts()

kepoi_name
K00752.01    1
K04976.01    1
K04978.01    1
K04979.01    1
K04980.01    1
            ..
K00552.01    1
K00601.01    1
K00601.02    1
K00601.03    1
K07989.01    1
Name: count, Length: 9564, dtype: int64

In [104]:
df_clean_cumu.drop('kepoi_name',axis=1,inplace=True)

In [105]:
df_clean_cumu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kepid            9564 non-null   int64
 1   koi_disposition  9564 non-null   object
 2   koi_period       9564 non-null   float64
 3   koi_eccen        9201 non-null   float64
 4   koi_impact       9201 non-null   float64
 5   koi_duration     9564 non-null   float64
 6   koi_depth        9201 non-null   float64
 7   koi_ror          9201 non-null   float64
 8   koi_prad         9201 non-null   float64
 9   koi_sma          9201 non-null   float64
 10  koi_incl         9200 non-null   float64
 11  koi_teq          9201 non-null   float64
 12  koi_insol        9243 non-null   float64
 13  koi_dor          9201 non-null   float64
 14  koi_steff        9201 non-null   float64
 15  koi_slogg        9201 non-null   float64
 16  koi_smet         9178 non-null   float64
 17  koi_srad         9201 non-null   float64
 18  koi_smass        9201 non-null   float64
 19  koi_kepmag       9563 non-null   float64
 20  koi_gmag         9523 non-null   float64
 21  koi_rmag         9555 non-null   float64
 22  koi_imag         9410 non-null   float64
 23  koi_zmag         8951 non-null   float64
 24  koi_jmag         9539 non-null   float64
 25  koi_hmag         9539 non-null   float64
 26  koi_kmag         9539 non-null   float64
dtypes: float64(25), int64(1), object(1)
memory usage: 2.0+ MB

In [106]:
df_clean_cumu.isnull().sum()

kepid                0
koi_disposition      0
koi_period           0
koi_eccen          363
koi_impact         363
koi_duration         0
koi_depth          363
koi_ror            363
koi_prad           363
koi_sma            363
koi_incl           364
koi_teq            363
koi_insol          321
koi_dor            363
koi_steff          363
koi_slogg          363
koi_smet           386
koi_srad           363
koi_smass          363
koi_kepmag           1
koi_gmag            41
koi_rmag             9
koi_imag           154
koi_zmag           613
koi_jmag            25
koi_hmag            25
koi_kmag            25
dtype: int64

In [107]:
df_clean_cumu['koi_eccen'].value_counts()

koi_eccen
0.0    9201
Name: count, dtype: int64

In [108]:
df_clean_cumu.drop('koi_eccen',axis=1,inplace=True)

In [109]:
df_clean_cumu['koi_impact'].isnull().sum()

363

In [110]:
df_clean_cumu.fillna(df_clean_cumu['koi_impact'].median(),inplace=True)

In [111]:
df_clean_cumu['koi_impact'].isnull().sum()

0

In [112]:
df_clean_cumu['koi_depth'].fillna(df_clean_cumu['koi_depth'].median(),inplace=True)

D:\Temp\ipykernel_20248\2659557907.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu['koi_depth'].fillna(df_clean_cumu['koi_depth'].median(),inplace=True)

In [113]:
df_clean_cumu['koi_depth'].isnull().sum()

0

In [114]:
df_clean_cumu['koi_ror'].fillna(df_clean_cumu['koi_ror'].median(),inplace=True)

D:\Temp\ipykernel_20248\254480680.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu['koi_ror'].fillna(df_clean_cumu['koi_ror'].median(),inplace=True)

In [115]:
# List of columns you want to fill with median
cols_to_fill = [
    "koi_prad", "koi_sma", "koi_incl", "koi_teq", "koi_insol", "koi_dor",
    "koi_steff", "koi_slogg", "koi_smet", "koi_srad", "koi_smass",
    "koi_kepmag", "koi_gmag", "koi_rmag", "koi_imag", "koi_zmag",
    "koi_jmag", "koi_hmag", "koi_kmag"
]

# Fill NaNs with median for each column
for col in cols_to_fill:
    if col in df_clean_cumu.columns:
        df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)

# Check if all nulls are gone
print(df_clean_cumu[cols_to_fill].isnull().sum())

koi_prad      0
koi_sma       0
koi_incl      0
koi_teq       0
koi_insol     0
koi_dor       0
koi_steff     0
koi_slogg     0
koi_smet      0
koi_srad      0
koi_smass     0
koi_kepmag    0
koi_gmag      0
koi_rmag      0
koi_imag      0
koi_zmag      0
koi_jmag      0
koi_hmag      0
koi_kmag      0
dtype: int64

D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)
D:\Temp\ipykernel_20248\3922081029.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean_cumu[col].fillna(df_clean_cumu[col].median(), inplace=True)

In [116]:
df_clean_cumu.isnull().sum()

kepid              0
koi_disposition    0
koi_period         0
koi_impact         0
koi_duration       0
koi_depth          0
koi_ror            0
koi_prad           0
koi_sma            0
koi_incl           0
koi_teq            0
koi_insol          0
koi_dor            0
koi_steff          0
koi_slogg          0
koi_smet           0
koi_srad           0
koi_smass          0
koi_kepmag         0
koi_gmag           0
koi_rmag           0
koi_imag           0
koi_zmag           0
koi_jmag           0
koi_hmag           0
koi_kmag           0
dtype: int64

In [117]:
df_clean_cumu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kepid            9564 non-null   int64
 1   koi_disposition  9564 non-null   object
 2   koi_period       9564 non-null   float64
 3   koi_impact       9564 non-null   float64
 4   koi_duration     9564 non-null   float64
 5   koi_depth        9564 non-null   float64
 6   koi_ror          9564 non-null   float64
 7   koi_prad         9564 non-null   float64
 8   koi_sma          9564 non-null   float64
 9   koi_incl         9564 non-null   float64
 10  koi_teq          9564 non-null   float64
 11  koi_insol        9564 non-null   float64
 12  koi_dor          9564 non-null   float64
 13  koi_steff        9564 non-null   float64
 14  koi_slogg        9564 non-null   float64
 15  koi_smet         9564 non-null   float64
 16  koi_srad         9564 non-null   float64
 17  koi_smass        9564 non-null   float64
 18  koi_kepmag       9564 non-null   float64
 19  koi_gmag         9564 non-null   float64
 20  koi_rmag         9564 non-null   float64
 21  koi_imag         9564 non-null   float64
 22  koi_zmag         9564 non-null   float64
 23  koi_jmag         9564 non-null   float64
 24  koi_hmag         9564 non-null   float64
 25  koi_kmag         9564 non-null   float64
dtypes: float64(24), int64(1), object(1)
memory usage: 1.9+ MB

In [118]:
df_clean_cumu['kepid']

0       10797460
1       10797460
2       10811496
3       10848459
4       10854555
          ...
9559    10090151
9560    10128825
9561    10147276
9562    10155286
9563    10156110
Name: kepid, Length: 9564, dtype: int64

In [119]:
X=df_clean_cumu.drop('koi_disposition',axis=1)
y=df_clean_cumu['koi_disposition']

In [120]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y=encoder.fit_transform(y)
y

array([1, 1, 0, ..., 2, 0, 2])

In [121]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [122]:
from sklearn.ensemble import RandomForestClassifier

In [123]:
model = RandomForestClassifier(n_estimators=100)

In [124]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [125]:
y_pred=model.predict(X_test)

In [126]:
y_pred_train = model.predict(X_train)

In [127]:
accuracy_score(y_pred_train,y_train)

1.0

In [128]:
from sklearn.metrics import accuracy_score,classification_report

In [129]:
accuracy_score(y_pred,y_test)

0.7505226480836237

In [130]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.41      0.54      0.46       467
           1       0.83      0.77      0.80       895
           2       0.85      0.80      0.83      1508

    accuracy                           0.75      2870
   macro avg       0.70      0.70      0.70      2870
weighted avg       0.77      0.75      0.76      2870

In [131]:
df_clean_cumu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kepid            9564 non-null   int64
 1   koi_disposition  9564 non-null   object
 2   koi_period       9564 non-null   float64
 3   koi_impact       9564 non-null   float64
 4   koi_duration     9564 non-null   float64
 5   koi_depth        9564 non-null   float64
 6   koi_ror          9564 non-null   float64
 7   koi_prad         9564 non-null   float64
 8   koi_sma          9564 non-null   float64
 9   koi_incl         9564 non-null   float64
 10  koi_teq          9564 non-null   float64
 11  koi_insol        9564 non-null   float64
 12  koi_dor          9564 non-null   float64
 13  koi_steff        9564 non-null   float64
 14  koi_slogg        9564 non-null   float64
 15  koi_smet         9564 non-null   float64
 16  koi_srad         9564 non-null   float64
 17  koi_smass        9564 non-null   float64
 18  koi_kepmag       9564 non-null   float64
 19  koi_gmag         9564 non-null   float64
 20  koi_rmag         9564 non-null   float64
 21  koi_imag         9564 non-null   float64
 22  koi_zmag         9564 non-null   float64
 23  koi_jmag         9564 non-null   float64
 24  koi_hmag         9564 non-null   float64
 25  koi_kmag         9564 non-null   float64
dtypes: float64(24), int64(1), object(1)
memory usage: 1.9+ MB